#!/usr/bin/env python3
"""
Cardan Grille Generator — VMS Structural Signature Test
========================================================

Tests whether a Cardan grille generator can reproduce the four structural
signatures of the Voynich Manuscript, and compares it against the slot-based
generator from signatures_v26.py.

Background
----------
Rugg (2004) proposed that the VMS could be meaningless output generated by a
Cardan grille applied to a lookup table.  The grille is a card with holes; it
is placed over a table of graphemes, and the visible cells are read off to form
a "word".  Repositioning the grille produces the next word.

Structural properties of this model:
  - Each word's graphemes are drawn from fixed table COLUMNS (slot structure).
  - If left/right columns contain different graphemes, the model produces
    prefix/suffix positional bias -> Signatures 1 and 2.
  - Words are generated independently (no Markov sequencing) in Rugg's original
    model -> Signature 3 (MI) is expected to be very low.
  - Blank cells create word-length variation; column frequency skew can produce
    Zipfian boundary distributions -> Signature 4 may or may not appear.

The grille model is therefore a constrained special case of our slot-based
generator: it has positional slot structure but (in the standard form) no
sequential word-to-word dependencies.

The key scientific question: can the grille model hit all four signatures
simultaneously, or does it face the same Sig3/Sig4 tension we found in the
slot-based generator?

Model design
------------
GrilleTable: a matrix of (table_rows x table_cols) cells.
  - Each cell is either blank or contains a grapheme drawn from a column-specific pool.
  - Left columns draw from PREFIX_CORE graphemes; right columns from SUFFIX_CORE.
  - blank_prob controls the probability that any given cell is blank.
  - col_skew (Zipf alpha) controls how concentrated each column's distribution is.

Grille: a binary mask of length table_cols with exactly n_holes ones.
  - The grille is applied to a randomly selected row of the table.
  - Non-blank cells at hole positions are concatenated to form a word.
  - Short words (< 2 graphemes) are discarded and redrawn.

Corpus generation modes:
  RANDOM   Each word uses a freshly sampled random grille position (Rugg's model).
           Words are independent -> MI expected ~0.
  SHIFT    Grille shifts right by 1 column after each word, wrapping around.
           Creates positional correlation between consecutive words -> some MI.
  ROTATE   A fixed set of grille masks is cycled through in order.
           Simulates the rotation mechanism in Rugg's original proposal.

Column specialisation modes:
  NONE     All columns draw from the full grapheme pool (no positional structure).
  SPLIT    Left half of columns draw from PREFIX_CORE; right half from SUFFIX_CORE.
  GRADIENT Left columns are increasingly prefix-weighted; right increasingly suffix.

Ablations
---------
  Main:
    G0   SPLIT + RANDOM    (structured table, independent words — Rugg's core model)
    G1   SPLIT + SHIFT     (structured table, shifted grille — adds positional MI)
    G2   SPLIT + ROTATE    (structured table, rotating grille — Rugg's rotation)
    G3   NONE  + RANDOM    (unstructured table, independent words — null model)
    G4   GRADIENT + RANDOM (gradient specialisation, independent words)

  Near-miss falsifications (mirroring signatures_v26 falsification section):
    G5   SPLIT + SHIFT + high col_skew (alpha=2.0)
    G6   SPLIT + RANDOM + boundary-pair-weighted row selection (adds MI injection)

  Sensitivity sweeps:
    S1   blank_prob   (0.0, 0.1, 0.2, 0.3, 0.4, 0.5)
    S2   n_holes      (2, 3, 4, 5, 6)
    S3   table_cols   (6, 8, 10, 12, 16)
    S4   col_skew     (0.0, 0.5, 1.0, 1.5, 2.0)
    S5   table_rows   (4, 8, 16, 32, 64)

Usage
-----
  python grille.py [--runs N] [--seed N] [--words N] [--fast]
                   [--part all|main|sensitivity|falsify]

  Requires signatures_v26.py in the same directory (imports evaluation pipeline).
"""

import argparse
import math
import random
import sys
import os
from collections import Counter, defaultdict
from typing import Dict, List, Optional, Tuple

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import signatures_v26 as ev   # evaluation pipeline

# ============================================================================
# GRAPHEME POOLS  (reuse from signatures_v26 for comparability)
# ============================================================================

PREFIX_GRAPHEMES = (
    ev.BRIDGE_CANDIDATES[:2] +               # o, a  (bridge)
    ev.PREFIX_CORE[0] +                      # q d s t k p f c
    ev.PREFIX_CORE[1] +                      # ch sh ck cth cph
    ev.PREFIX_CORE[2] +                      # ok ot ol or
    ev.PREFIX_CORE[3] +                      # k2 t2 p2 f2 d2 s2
    ev.PREFIX_CORE[4]                        # ch2 sh2 ckh cth2 cfh
)

SUFFIX_GRAPHEMES = (
    ev.BRIDGE_CANDIDATES[:2] +               # o, a  (bridge)
    ev.SUFFIX_CORE[1] +                      # dy dl dm ds dar dal
    ev.SUFFIX_CORE[2] +                      # iin in ir iir iiir
    ev.SUFFIX_CORE[3] +                      # al am an ar ain aiin
    ev.SUFFIX_CORE[4] +                      # ey ed es edy eey eedy
    ev.SUFFIX_CORE[5]                        # ly ry ny my ldy
)

ALL_GRAPHEMES = sorted(
    set(PREFIX_GRAPHEMES) | set(SUFFIX_GRAPHEMES),
    key=lambda x: (-len(x), x)
)

TOKENIZER = ev.make_greedy_tokenizer(ALL_GRAPHEMES)


# ============================================================================
# GRILLE TABLE BUILDER
# ============================================================================

def _column_pool(col_idx: int, table_cols: int, specialisation: str) -> List[str]:
    """
    Return the grapheme pool for a given column index.

    NONE / UNIFORM / BLANK_GRADIENT
        All columns draw from the full pool — no positional separation.
        NONE/UNIFORM: blank_prob is uniform across columns (set in build_table).
        BLANK_GRADIENT: blank_prob increases left-to-right (set in build_table).
        Use table_rows >= 256 to avoid sampling artefacts.

    SPLIT  [*** CIRCULAR — kept for comparison only ***]
        Left half uses PREFIX_GRAPHEMES, right half SUFFIX_GRAPHEMES.
        Bakes in the very structure being tested.

    GRADIENT  [also partially circular]
        Columns blend from prefix-dominant to suffix-dominant.
    """
    if specialisation in ("NONE", "UNIFORM", "BLANK_GRADIENT"):
        return list(ALL_GRAPHEMES)

    frac = col_idx / max(table_cols - 1, 1)

    if specialisation == "SPLIT":
        return list(PREFIX_GRAPHEMES) if frac < 0.5 else list(SUFFIX_GRAPHEMES)

    if specialisation == "GRADIENT":
        n_pref = max(1, round((1 - frac) * len(PREFIX_GRAPHEMES)))
        n_suf  = max(1, round(frac       * len(SUFFIX_GRAPHEMES)))
        pool   = PREFIX_GRAPHEMES[:n_pref] + SUFFIX_GRAPHEMES[:n_suf]
        return list(set(pool)) if pool else list(ALL_GRAPHEMES)

    raise ValueError(f"Unknown specialisation: {specialisation}")


def build_table(table_rows: int, table_cols: int,
                specialisation: str = "SPLIT",
                blank_prob: float = 0.2,
                col_skew: float = 1.2,
                rng: Optional[random.Random] = None) -> List[List[Optional[str]]]:
    """
    Build a (table_rows x table_cols) grille table.

    For BLANK_GRADIENT specialisation, blank_prob is the *maximum* blank
    probability (applied to the rightmost column); the leftmost column has
    blank_prob=0.  This tests whether density variation alone — without any
    pool separation — can induce positional grapheme structure.

    For all other specialisations, blank_prob is uniform across columns.
    """
    if rng is None:
        rng = random.Random()

    table = []
    for _row in range(table_rows):
        row = []
        for col in range(table_cols):
            # Column-specific blank probability
            if specialisation == "BLANK_GRADIENT":
                frac = col / max(table_cols - 1, 1)
                col_blank = blank_prob * frac   # 0 at left, blank_prob at right
            else:
                col_blank = blank_prob

            if rng.random() < col_blank:
                row.append(None)
            else:
                pool = _column_pool(col, table_cols, specialisation)
                if not pool:
                    row.append(None)
                    continue
                if col_skew < 0.01:
                    g = rng.choice(pool)
                else:
                    weights = ev.make_zipf_weights(len(pool), col_skew)
                    g = rng.choices(pool, weights=weights, k=1)[0]
                row.append(g)
        table.append(row)
    return table


def build_table_from_corpus(sentences, tokenizer,
                             table_cols: int = 10,
                             table_rows: int = 256,
                             col_skew: float = 0.0,
                             rng: Optional[random.Random] = None
                             ) -> List[List[Optional[str]]]:
    """
    Build a grille table whose COLUMN DISTRIBUTIONS are learned from a real
    corpus rather than from pre-separated prefix/suffix pools.

    Method:
      1. For each word in the corpus, tokenize it and record which grapheme
         appears at each word-position index (0=first, 1=second, ...).
      2. This gives an empirical distribution P(grapheme | position).
      3. Map word-position indices to table columns: position i -> column i
         (capped at table_cols - 1).
      4. Fill each table cell by sampling from the column's learned distribution.

    If col_skew > 0, the sampling is further concentrated by Zipfian reweighting
    of the empirical distribution.  col_skew=0 (default) uses the raw empirical
    frequencies.

    This is the HONEST version of pool-based specialisation: the positional
    structure in the table reflects whatever positional structure exists in the
    source corpus — no structure is imposed by construction.

    Source corpora used:
      G8: English (Moby Dick)   — natural language with real positional structure
      G9: VMS Markov baseline   — slot-based synthetic text (circular but explicit)
      G10: Random EVA sequences  — structureless baseline; expected E->S ~0
    """
    if rng is None:
        rng = random.Random()

    # Build positional frequency counts
    pos_counts: List[Counter] = [Counter() for _ in range(table_cols)]
    for sent in sentences:
        for w in sent:
            toks = tokenizer(w)
            for i, g in enumerate(toks[:table_cols]):
                pos_counts[i][g] += 1

    # Convert to weighted pool per column
    col_pools: List[List[str]] = []
    col_weights: List[List[float]] = []
    for col in range(table_cols):
        cnt = pos_counts[col]
        if not cnt:
            # No data for this position: fall back to uniform full pool
            col_pools.append(list(ALL_GRAPHEMES))
            col_weights.append(ev.make_flat_weights(len(ALL_GRAPHEMES)))
        else:
            graphemes = list(cnt.keys())
            freqs     = [cnt[g] for g in graphemes]
            if col_skew < 0.01:
                total = sum(freqs)
                weights = [f / total for f in freqs]
            else:
                # Reweight by rank with Zipfian exponent
                ranked   = sorted(range(len(freqs)), key=lambda i: -freqs[i])
                zipf_w   = ev.make_zipf_weights(len(freqs), col_skew)
                weights  = [0.0] * len(freqs)
                for rank, idx in enumerate(ranked):
                    weights[idx] = zipf_w[rank]
            col_pools.append(graphemes)
            col_weights.append(weights)

    # Fill table by sampling from learned column distributions
    table = []
    for _ in range(table_rows):
        row = []
        for col in range(table_cols):
            g = rng.choices(col_pools[col], weights=col_weights[col], k=1)[0]
            row.append(g)
        table.append(row)
    return table


# ============================================================================
# GRILLE APPLICATION
# ============================================================================

def apply_grille(table: List[List[Optional[str]]],
                 hole_positions: List[int],
                 rng: Optional[random.Random] = None) -> str:
    """
    Apply a grille (defined by its hole positions) to a randomly selected
    table row.  Concatenate non-blank graphemes at hole positions.
    Returns the resulting word (may be empty string if all cells are blank).
    """
    if rng is None:
        rng = random.Random()
    row = rng.choice(table)
    graphemes = [row[p] for p in hole_positions if p < len(row) and row[p] is not None]
    return "".join(graphemes)


def random_grille(table_cols: int, n_holes: int, rng: random.Random) -> List[int]:
    """Return a random grille: n_holes distinct column positions."""
    return sorted(rng.sample(range(table_cols), min(n_holes, table_cols)))


def shift_grille(current_holes: List[int], table_cols: int) -> List[int]:
    """Shift all hole positions right by 1, wrapping around."""
    return [(p + 1) % table_cols for p in current_holes]


def rotate_grilles(table_cols: int, n_holes: int) -> List[List[int]]:
    """
    Generate all unique rotations of a grille with holes at positions 0..n_holes-1.
    Returns a list of hole-position lists.
    """
    base = list(range(n_holes))
    rotations = []
    current = base[:]
    for _ in range(table_cols):
        rotations.append(sorted(current))
        current = [(p + 1) % table_cols for p in current]
    # Deduplicate
    seen = set()
    unique = []
    for r in rotations:
        key = tuple(r)
        if key not in seen:
            seen.add(key)
            unique.append(r)
    return unique


# ============================================================================
# CORPUS GENERATORS
# ============================================================================

def generate_corpus_random(table, table_cols, n_holes, n_words, rng):
    """
    Rugg's core model: each word uses a freshly sampled random grille position.
    Words are generated independently — no sequential structure.
    """
    words = []
    attempts = 0
    while len(words) < n_words and attempts < n_words * 20:
        attempts += 1
        holes = random_grille(table_cols, n_holes, rng)
        w = apply_grille(table, holes, rng)
        if len(w) >= 2:
            words.append(w)
    return words


def generate_corpus_shift(table, table_cols, n_holes, n_words, rng):
    """
    Shifted grille: the grille moves right by 1 column after each word.
    Creates positional correlation between consecutive words (some MI expected).
    """
    holes = random_grille(table_cols, n_holes, rng)
    words = []
    attempts = 0
    while len(words) < n_words and attempts < n_words * 20:
        attempts += 1
        w = apply_grille(table, holes, rng)
        if len(w) >= 2:
            words.append(w)
        holes = shift_grille(holes, table_cols)
    return words


def generate_corpus_rotate(table, table_cols, n_holes, n_words, rng):
    """
    Rotating grille: cycles through all unique rotations of a fixed grille mask.
    Closer to Rugg's original rotating card mechanism.
    """
    rotations = rotate_grilles(table_cols, n_holes)
    if not rotations:
        return generate_corpus_random(table, table_cols, n_holes, n_words, rng)
    words = []
    attempts = 0
    rot_idx = 0
    while len(words) < n_words and attempts < n_words * 20:
        attempts += 1
        holes = rotations[rot_idx % len(rotations)]
        w = apply_grille(table, holes, rng)
        if len(w) >= 2:
            words.append(w)
        rot_idx += 1
    return words


def generate_corpus_weighted_rows(table, table_cols, n_holes, n_words, rng,
                                  boundary_pairs=None, pair_strength=3.0):
    """
    Near-miss variant G6: boundary-pair-weighted row selection.
    After generating a word, the next word's row is biased toward rows whose
    leftmost non-blank cell matches a preferred (prev_end, next_start) pair.
    This injects a small amount of MI without full Markov machinery.
    """
    # Pre-build: for each (end_grapheme, start_grapheme) pair in boundary_pairs,
    # track which rows produce that start grapheme.
    pair_bonus = {}
    if boundary_pairs:
        for entry in boundary_pairs:
            eg, sg = entry[0], entry[1]
            st = entry[2] if len(entry) == 3 else pair_strength
            pair_bonus[(eg, sg)] = st

    def _get_start(row, holes):
        for p in sorted(holes):
            if p < len(row) and row[p] is not None:
                return row[p]
        return None

    def _get_end(word_str):
        toks = TOKENIZER(word_str)
        return toks[-1] if toks else None

    holes = random_grille(table_cols, n_holes, rng)
    words = []
    prev_end = None
    attempts = 0

    while len(words) < n_words and attempts < n_words * 30:
        attempts += 1
        # Weight rows by whether their start matches a preferred pair
        if prev_end and pair_bonus:
            row_weights = []
            for row in table:
                sg = _get_start(row, holes)
                bonus = pair_bonus.get((prev_end, sg), 1.0) if sg else 1.0
                row_weights.append(bonus)
            total = sum(row_weights)
            row_weights = [w / total for w in row_weights]
            chosen_row = rng.choices(table, weights=row_weights, k=1)[0]
        else:
            chosen_row = rng.choice(table)

        graphemes = [chosen_row[p] for p in holes
                     if p < len(chosen_row) and chosen_row[p] is not None]
        w = "".join(graphemes)
        if len(w) >= 2:
            words.append(w)
            prev_end = _get_end(w)
        holes = shift_grille(holes, table_cols)

    return words


def load_english_corpus(path: str) -> List[str]:
    """
    Load a plain-text English corpus and return a list of lowercase words.
    Punctuation is stripped; words shorter than 2 characters are dropped.
    Used as the source for G_seq_English configs.
    """
    import re
    words = []
    try:
        with open(path, encoding="utf-8", errors="replace") as f:
            for line in f:
                for w in line.split():
                    w = re.sub(r"[^a-zA-Z]", "", w).lower()
                    if len(w) >= 2:
                        words.append(w)
    except FileNotFoundError:
        raise FileNotFoundError(
            "English corpus not found at '" + path + "'. "
            "Set --english-path to the location of the file. "
            "Expected format: plain text, one paragraph per line."
        )
    return words


def generate_corpus_sequential(source_words: List[str],
                                n_holes: int,
                                n_words: int,
                                p_jump: float,
                                rng: Optional[random.Random] = None) -> List[str]:
    """
    Row-sequential grille traversal over a table whose rows are the characters
    of successive source words.

    Mechanism:
      - Table row i = character list of source_words[i].
      - The grille selects n_holes random character positions from the current row.
      - After each word, advance to the next row with probability (1 - p_jump);
        with probability p_jump, jump to a uniformly random row.

    Variants (controlled by p_jump):
      p_jump = 0.0   pure sequential (rows visited in order, wrapping)
      p_jump = 0.0 with occasional perturbation  (e.g. p_jump = 0.05 or 0.1)
      p_jump = 1.0   pure random (Rugg's original model, rows drawn uniformly)

    Key property: any MI in the output is BOUNDED ABOVE by the MI in the source.
    The grille cannot create MI ex nihilo — it can only transmit or attenuate
    whatever sequential structure exists in the row ordering.

    With an English source: net MI decreases monotonically from ~0.64 (p=0.0)
    to ~0 (p=1.0), giving a clean falsifiable sweep.
    With a random source: net MI ≈ 0 for all p_jump values (validated empirically).
    """
    if rng is None:
        rng = random.Random()

    n_rows = len(source_words)
    if n_rows == 0:
        return []

    row_idx = 0
    words_out: List[str] = []
    attempts = 0

    while len(words_out) < n_words and attempts < n_words * 20:
        attempts += 1
        row = list(source_words[row_idx % n_rows])
        if not row:
            row_idx = (row_idx + 1) % n_rows
            continue

        k = min(n_holes, len(row))
        holes = sorted(rng.sample(range(len(row)), k))
        w = "".join(row[p] for p in holes)
        if len(w) >= 2:
            words_out.append(w)

        # Advance row pointer
        if rng.random() < p_jump:
            row_idx = rng.randint(0, n_rows - 1)
        else:
            row_idx = (row_idx + 1) % n_rows

    return words_out


def words_to_sentences(words, min_len=4, max_len=12, rng=None):
    if rng is None:
        rng = random.Random()
    sentences, i = [], 0
    while i < len(words):
        n = rng.randint(min_len, max_len)
        s = words[i:i + n]
        if len(s) >= 3:
            sentences.append(s)
        i += n
    return sentences


# ============================================================================
# GRILLE CONFIG CLASS
# ============================================================================

class GrilleConfig:
    """
    Mirrors the GeneratorConfig interface from signatures_v26 so the same
    run_config / aggregate / print functions can be used unchanged.
    """

    def __init__(self, label: str,
                 table_rows: int = 16,
                 table_cols: int = 10,
                 n_holes: int = 4,
                 specialisation: str = "SPLIT",
                 blank_prob: float = 0.2,
                 col_skew: float = 1.2,
                 mode: str = "RANDOM",
                 boundary_pairs=None,
                 pair_strength: float = 3.0,
                 n_words: int = 37000,
                 source_corpus=None,
                 source_tokenizer=None,
                 **kwargs):
        self.label            = label
        self.table_rows       = table_rows
        self.table_cols       = table_cols
        self.n_holes          = n_holes
        self.specialisation   = specialisation
        self.blank_prob       = blank_prob
        self.col_skew         = col_skew
        self.mode             = mode
        self.boundary_pairs   = boundary_pairs
        self.pair_strength    = pair_strength
        self.n_words          = n_words
        self.source_corpus    = source_corpus     # pre-built sentences for learned table
        self.source_tokenizer = source_tokenizer  # tokenizer for source corpus
        self.tokenizer        = TOKENIZER
        self.n_graphemes      = len(ALL_GRAPHEMES)
        self.vocab_size       = table_rows  # for display
        # Row-sequential parameters (used when mode == "SEQUENTIAL")
        self.p_jump           = kwargs.get("p_jump", 0.0)
        self.source_words     = kwargs.get("source_words", None)

    def generate(self, seed: int = 42) -> List[List[str]]:
        rng = random.Random(seed)
        if self.source_corpus is not None:
            # Honest table: column distributions learned from real corpus
            src_tok = self.source_tokenizer or TOKENIZER
            table = build_table_from_corpus(
                self.source_corpus, src_tok,
                table_cols=self.table_cols,
                table_rows=self.table_rows,
                col_skew=self.col_skew,
                rng=rng)
        else:
            table = build_table(self.table_rows, self.table_cols,
                                self.specialisation, self.blank_prob,
                                self.col_skew, rng)

        if self.mode == "SEQUENTIAL":
            # Row-sequential: uses source_words directly, not a table
            if self.source_words is None:
                raise ValueError(
                    "SEQUENTIAL mode requires source_words. "
                    "Pass source_words=load_english_corpus(path) or "
                    "source_words=random_word_list to the config.")
            words = generate_corpus_sequential(
                self.source_words, self.n_holes, self.n_words,
                self.p_jump, rng)
        elif self.mode == "RANDOM":
            words = generate_corpus_random(
                table, self.table_cols, self.n_holes, self.n_words, rng)
        elif self.mode == "SHIFT":
            words = generate_corpus_shift(
                table, self.table_cols, self.n_holes, self.n_words, rng)
        elif self.mode == "ROTATE":
            words = generate_corpus_rotate(
                table, self.table_cols, self.n_holes, self.n_words, rng)
        elif self.mode == "WEIGHTED":
            words = generate_corpus_weighted_rows(
                table, self.table_cols, self.n_holes, self.n_words, rng,
                self.boundary_pairs, self.pair_strength)
        else:
            raise ValueError(f"Unknown mode: {self.mode}")

        return words_to_sentences(words, rng=rng)


# ============================================================================
# CONFIG FACTORIES
# ============================================================================

def build_honest_source_corpora():
    """
    Build the three source corpora used to fill learned tables (G8/G9/G10).
    Called once at startup to avoid regenerating per run.

    Returns a dict: name -> (sentences, tokenizer)
    """
    corpora = {}

    # G8: English (Moby Dick) — real natural language positional structure
    en_sents, en_tok = ev.make_english_control()
    corpora["english"] = (en_sents, en_tok)

    # G9: VMS Markov baseline corpus — slot-structured synthetic text
    #     Circular (uses our own generator) but explicitly labelled as such.
    #     Tests: if you know the VMS structure and build a table from it,
    #     can a grille reproduce the signatures?
    vms_cfg   = ev.cfg_baseline(n_words=37000)
    vms_sents = vms_cfg.generate(seed=0)
    corpora["vms_markov"] = (vms_sents, TOKENIZER)

    # G10: Random EVA grapheme sequences — structureless baseline
    #      Expected: table has no positional bias -> E->S ~0
    rng = random.Random(0)
    rand_words = [
        "".join(rng.choice(ALL_GRAPHEMES) for _ in range(rng.randint(2, 5)))
        for _ in range(37000)
    ]
    rand_sents, i = [], 0
    while i < len(rand_words):
        n = rng.randint(4, 12); s = rand_words[i:i+n]
        if len(s) >= 3: rand_sents.append(s)
        i += n
    corpora["random"] = (rand_sents, TOKENIZER)

    return corpora


def grille_configs(n_words=37000):
    """
    Main ablation configs.

    G0-G4: original configs with pre-separated pools (SPLIT/NONE/GRADIENT).
           Kept for comparison but G0/G1/G2 are circular on Signature 1.

    G8-G10: HONEST configs — table filled from real corpora, no pre-separation.
           These directly address the reviewer criticism.
           Source corpora must be built first via build_honest_source_corpora().
    """
    return [
        # --- Pool-separated configs (circular on Sig1, kept for comparison) ---
        GrilleConfig("G0  SPLIT+RANDOM   [Rugg core, circular]",
                     specialisation="SPLIT",  mode="RANDOM",  n_words=n_words),
        GrilleConfig("G1  SPLIT+SHIFT    [positional MI, circular]",
                     specialisation="SPLIT",  mode="SHIFT",   n_words=n_words),
        GrilleConfig("G2  SPLIT+ROTATE   [Rugg rotation, circular]",
                     specialisation="SPLIT",  mode="ROTATE",  n_words=n_words),
        GrilleConfig("G3  UNIFORM+RANDOM [no structure, rows=256]",
                     specialisation="UNIFORM", mode="RANDOM",
                     table_rows=256, n_words=n_words),
        GrilleConfig("G4  GRADIENT+RANDOM [gradient, circular]",
                     specialisation="GRADIENT", mode="RANDOM", n_words=n_words),
        # --- Honest mechanism test: density gradient, no pool separation ---
        GrilleConfig("G5  BLANK-GRADIENT+RANDOM [density only]",
                     specialisation="BLANK_GRADIENT", mode="RANDOM",
                     blank_prob=0.6, table_rows=256, n_words=n_words),
    ]


def grille_honest_configs(n_words=37000, corpora=None):
    """
    Honest configs: table column distributions learned from real corpora.
    No prefix/suffix pool separation imposed by construction.

    G8: Table from English text  -> tests natural language structure
    G9: Table from VMS Markov    -> tests slot-structured synthetic source
    G10: Table from random seqs  -> structureless baseline (expected E->S ~0)

    All use RANDOM grille mode (Rugg's original independent-word model).
    """
    if corpora is None:
        corpora = build_honest_source_corpora()

    en_sents,  en_tok  = corpora["english"]
    vms_sents, vms_tok = corpora["vms_markov"]
    rand_sents, r_tok  = corpora["random"]

    return [
        GrilleConfig("G8  LEARNED-ENGLISH+RANDOM [honest]",
                     table_rows=256, table_cols=10, n_holes=4,
                     mode="RANDOM", col_skew=0.0,
                     source_corpus=en_sents, source_tokenizer=en_tok,
                     n_words=n_words),
        GrilleConfig("G9  LEARNED-VMS+RANDOM [honest, explicit]",
                     table_rows=256, table_cols=10, n_holes=4,
                     mode="RANDOM", col_skew=0.0,
                     source_corpus=vms_sents, source_tokenizer=vms_tok,
                     n_words=n_words),
        GrilleConfig("G10 LEARNED-RANDOM+RANDOM [honest null]",
                     table_rows=256, table_cols=10, n_holes=4,
                     mode="RANDOM", col_skew=0.0,
                     source_corpus=rand_sents, source_tokenizer=r_tok,
                     n_words=n_words),
    ]


def build_sequential_source_words(english_path: Optional[str] = None,
                                   n_words: int = 37000) -> Dict[str, List[str]]:
    """
    Build the word lists used as row sources for SEQUENTIAL configs.

    Returns a dict with three entries:
      "english"  — words from the real English corpus (requires --english-path)
      "random"   — random EVA grapheme sequences (structureless null)

    The English source is loaded fresh from disk each call so the script
    can be run on different machines without code changes.
    """
    sources = {}

    # English source
    if english_path:
        sources["english"] = load_english_corpus(english_path)
        print(f"    Loaded {len(sources['english'])} English words from {english_path}")
    else:
        # Fallback: tile the hardcoded Moby Dick snippet to ~5000 words
        en_sents, _ = ev.make_english_control()
        en_words = [w.lower() for sent in en_sents for w in sent]
        sources["english"] = (en_words * (5000 // len(en_words) + 1))[:5000]
        print(f"    English fallback: tiled Moby Dick snippet to {len(sources['english'])} words")
        print(f"    NOTE: use --english-path data/english.txt for full results")

    # Random EVA source (null baseline)
    rng = random.Random(999)
    sources["random"] = [
        "".join(rng.choice(ALL_GRAPHEMES) for _ in range(rng.randint(2, 6)))
        for _ in range(max(37000, len(sources["english"])))
    ]

    return sources


def grille_sequential_configs(n_words: int = 37000,
                               source_words: Optional[Dict[str, List[str]]] = None
                               ) -> List[GrilleConfig]:
    """
    Row-sequential grille configs — the honest, non-circular MI test.

    Scientific question:
      Can a Cardan grille transmit real sequential structure (from English)
      through to its output, generating MI comparable to the VMS?
      And does it simultaneously achieve Zipfian shape and E->S?

    Three source x four p_jump combinations:

      G_seq_E0   English, p_jump=0.00  (pure sequential — max MI ceiling)
      G_seq_E1   English, p_jump=0.05  (occasional jump — realistic scribe)
      G_seq_E2   English, p_jump=0.10
      G_seq_E3   English, p_jump=0.30
      G_seq_R0   Random,  p_jump=0.00  (null: sequential traversal, no source MI)
      G_seq_R1   Random,  p_jump=1.00  (Rugg baseline: random, no source MI)

    Expected results:
      G_seq_E0: highest MI (bounded by English MI ≈ 0.64); E->S low (English ~31%)
      G_seq_E* : MI decreases monotonically with p_jump
      G_seq_R* : MI ≈ 0 regardless of p_jump (no source structure to transmit)

    Interpretation:
      If no config hits MI ≈ 0.230 with E->S ≈ 80% simultaneously:
        The grille faces the same Sig3/Sig4 tension as the slot generator.
      If a config hits both:
        Rugg's model can explain the VMS joint profile.

    Note on circularity:
      English source: NOT circular (independent of our generator)
      Random source:  NOT circular (structureless null)
      VMS Markov source: CIRCULAR (explicitly excluded from this config set)
    """
    if source_words is None:
        source_words = {}

    eng_words  = source_words.get("english", [])
    rand_words = source_words.get("random", [])

    configs = []
    if eng_words:
        for p_jump, label_suffix in [
            (0.00, "p=0.00 [pure sequential]"),
            (0.05, "p=0.05 [realistic jump]"),
            (0.10, "p=0.10"),
            (0.30, "p=0.30"),
        ]:
            configs.append(GrilleConfig(
                f"G_seq English {label_suffix}",
                mode="SEQUENTIAL", n_holes=4, n_words=n_words,
                p_jump=p_jump, source_words=eng_words))

    if rand_words:
        for p_jump, label_suffix in [
            (0.00, "p=0.00 [sequential null]"),
            (1.00, "p=1.00 [random null]"),
        ]:
            configs.append(GrilleConfig(
                f"G_seq Random  {label_suffix}",
                mode="SEQUENTIAL", n_holes=4, n_words=n_words,
                p_jump=p_jump, source_words=rand_words))

    return configs


def grille_nearmiss_configs(n_words=37000):
    """Near-miss configs: high col_skew and/or boundary-weighted rows."""
    return [
        GrilleConfig("G5  SPLIT+SHIFT+skew2.0",
                     specialisation="SPLIT", mode="SHIFT",
                     col_skew=2.0, n_words=n_words),
        GrilleConfig("G6  SPLIT+WEIGHTED+pairs",
                     specialisation="SPLIT", mode="WEIGHTED",
                     col_skew=1.2,
                     boundary_pairs=ev.DEFAULT_BOUNDARY_PAIRS,
                     pair_strength=3.0, n_words=n_words),
        GrilleConfig("G7  SPLIT+WEIGHTED+skew2.0",
                     specialisation="SPLIT", mode="WEIGHTED",
                     col_skew=2.0,
                     boundary_pairs=ev.DEFAULT_BOUNDARY_PAIRS,
                     pair_strength=3.0, n_words=n_words),
    ]


def sens_blank_prob(n_words=37000):
    return [GrilleConfig(f"S1: blank={p:.1f}", specialisation="SPLIT",
                         mode="RANDOM", blank_prob=p, n_words=n_words)
            for p in [0.0, 0.1, 0.2, 0.3, 0.4, 0.5]]


def sens_n_holes(n_words=37000):
    return [GrilleConfig(f"S2: holes={h}", specialisation="SPLIT",
                         mode="RANDOM", n_holes=h, n_words=n_words)
            for h in [2, 3, 4, 5, 6]]


def sens_table_cols(n_words=37000):
    return [GrilleConfig(f"S3: cols={c}", specialisation="SPLIT",
                         mode="RANDOM", table_cols=c,
                         n_holes=max(2, c // 3), n_words=n_words)
            for c in [6, 8, 10, 12, 16]]


def sens_col_skew(n_words=37000):
    return [GrilleConfig(f"S4: skew={a:.1f}", specialisation="SPLIT",
                         mode="RANDOM", col_skew=a, n_words=n_words)
            for a in [0.0, 0.5, 1.0, 1.5, 2.0]]


def sens_table_rows(n_words=37000):
    return [GrilleConfig(f"S5: rows={r}", specialisation="SPLIT",
                         mode="RANDOM", table_rows=r, n_words=n_words)
            for r in [4, 8, 16, 32, 64]]


# ============================================================================
# RUNNERS  (reuse signatures_v26 aggregate/print infrastructure)
# ============================================================================

def run_grille_config(cfg: GrilleConfig, n_runs: int = 20,
                      base_seed: int = 42, n_shuffles: int = 3):
    results = []
    for i in range(n_runs):
        try:
            sents = cfg.generate(seed=base_seed + i * 137)
        except Exception as exc:
            print(f"\n  ERROR {cfg.label} run {i}: {exc}")
            import traceback; traceback.print_exc()
            continue
        results.append(
            ev.evaluate_corpus_fast(sents, cfg.tokenizer, cfg.label, n_shuffles))
    return results


def print_grille_table(agg_list, title="GRILLE ABLATION RESULTS"):
    W = 155
    print(f"\n{'='*W}")
    print(f"  {title}  (95% bootstrap CIs, Cohen's d vs VMS)")
    print(f"{'='*W}")
    print(f"  {'Config':<40} {'E->S% [CI]':>25} {'d':>7}  "
          f"{'MI [CI]':>25} {'d':>7}  {'Shape':>12}  {'Bil%':>5}  {'Joint':>5}")
    print(f"  {'-'*(W-2)}")

    for a in agg_list:
        es_s  = f"{a['es_pct_mean']:5.1f} [{a['es_pct_lo']:5.1f},{a['es_pct_hi']:5.1f}]"
        mi_s  = f"{a['mi_orig_mean']:.4f} [{a['mi_orig_lo']:.4f},{a['mi_orig_hi']:.4f}]"
        esd   = a.get("es_pct_d", float("nan"))
        mid   = a.get("mi_orig_d", float("nan"))
        esd_s = f"{esd:>+7.1f}" if math.isfinite(esd) else f"{'N/A':>7}"
        mid_s = f"{mid:>+7.1f}" if math.isfinite(mid) else f"{'N/A':>7}"
        _, nm = ev.joint_profile_match(a)
        print(f"  {a['label']:<40} {es_s:>25} {esd_s}  "
              f"{mi_s:>25} {mid_s}  {a['shape']:>12}  "
              f"{100*a['bilat_frac']:5.0f}  {nm:>4}/4")

    print(f"\n  {'VMS (observed)':<40} "
          f"{'80.6':>25} {'ref':>7}  "
          f"{'0.2300':>25} {'ref':>7}  "
          f"{'Zipfian':>12}  {'100':>5}  {'4/4':>5}")


def print_grille_sens_table(agg_list, param_name):
    print(f"\n{'='*130}")
    print(f"  GRILLE SENSITIVITY: {param_name}")
    print(f"{'='*130}")
    print(f"\n  {'Config':<28} {'E->S% [CI]':>25} {'Bil%':>5} "
          f"{'MI [CI]':>25} {'R2':>6} {'CV':>6} {'Shape':>12}  {'Joint':>5}")
    print(f"  {'-'*118}")
    for a in agg_list:
        es_s = f"{a['es_pct_mean']:5.1f} [{a['es_pct_lo']:5.1f},{a['es_pct_hi']:5.1f}]"
        mi_s = f"{a['mi_orig_mean']:.4f} [{a['mi_orig_lo']:.4f},{a['mi_orig_hi']:.4f}]"
        r2   = a.get("zipf_r2_mean", float("nan"))
        cv   = a.get("cv_mean",      float("nan"))
        _, nm = ev.joint_profile_match(a)
        print(f"  {a['label']:<28} {es_s:>25} {100*a['bilat_frac']:5.0f} "
              f"{mi_s:>25} {r2:6.3f} {cv:6.2f} {a['shape']:>12}  {nm:>4}/4")
    print(f"\n  VMS ref: E->S=80.6%  MI=0.230  Bilateral  R2=0.95  CV~1.0  Zipfian")


def print_grille_interpretation(agg_list):
    print(f"\n\n{'='*100}")
    print(f"  GRILLE INTERPRETATION MATRIX")
    print(f"{'='*100}")
    print(f"\n  {'Config':<40} {'E->S':>6} {'Bilat':>6} {'MI':>6} {'Zipf':>6}  {'Joint':>6}")
    print(f"  {'-'*75}")
    for a in agg_list:
        es = a["es_pct_mean"]; mi = a["mi_orig_mean"]
        s1 = "ok" if 70 <= es <= 95 else "~" if 60 <= es <= 98 else "x"
        s2 = "ok" if a["bilat_frac"] > 0.5 else "x"
        s3 = "ok" if mi > 0.10 else "~" if mi > 0.03 else "x"
        s4 = "ok" if a["shape"] == "Zipfian" \
             else "~" if a.get("zipf_r2_mean", 0) > 0.80 else "x"
        _, nm = ev.joint_profile_match(a)
        print(f"  {a['label']:<40} {s1:>6} {s2:>6} {s3:>6} {s4:>6}  {nm:>5}/4")
    print(f"\n  ok=VMS-like  ~=marginal  x=absent")
    print(f"  Sig1: E->S 70-95%  Sig2: bilateral >50% runs  "
          f"Sig3: MI>0.10  Sig4: Zipfian")


def print_comparison_summary(grille_agg, slot_label="C1 slot [best]",
                              slot_es=83.4, slot_mi=0.210,
                              slot_shape="Intermediate", slot_joint=3):
    """
    Print a side-by-side comparison of the best grille config vs the best
    slot-based config from the candidate sweep.
    """
    print(f"\n{'='*100}")
    print(f"  COMPARISON: BEST GRILLE vs BEST SLOT-BASED GENERATOR")
    print(f"{'='*100}")
    print(f"\n  {'Config':<45} {'E->S%':>8} {'MI':>8} {'Shape':>14} {'Joint':>6}")
    print(f"  {'-'*85}")

    best = max(grille_agg, key=lambda a: (ev.joint_profile_match(a)[1],
                                           a["mi_orig_mean"]))
    _, best_nm = ev.joint_profile_match(best)
    print(f"  {'Best grille: ' + best['label']:<45} "
          f"{best['es_pct_mean']:8.1f} {best['mi_orig_mean']:8.4f} "
          f"{best['shape']:>14} {best_nm:>5}/4")
    print(f"  {slot_label:<45} "
          f"{slot_es:8.1f} {slot_mi:8.4f} "
          f"{slot_shape:>14} {slot_joint:>5}/4")
    print(f"  {'VMS (observed)':<45} "
          f"{'80.6':>8} {'0.2300':>8} {'Zipfian':>14} {'4/4':>6}")

    print(f"\n  Key question: does the Cardan grille face the same Sig3/Sig4 tension")
    print(f"  as the slot-based generator, or does its different generative")
    print(f"  mechanism escape the trade-off?")

    all_best = [(ev.joint_profile_match(a)[1], a) for a in grille_agg]
    best_n   = max(n for n, _ in all_best)

    if best_n == 4:
        print(f"\n  RESULT: Grille hits 4/4 — the VMS joint profile IS replicable")
        print(f"  by a Cardan grille.  The four signatures do not rule out Rugg's")
        print(f"  gibberish hypothesis.")
    elif best_n == 3:
        checks, _ = ev.joint_profile_match(best)
        failing = [k for k, v in checks.items() if not v]
        print(f"\n  RESULT: Best grille is 3/4, failing on: {', '.join(failing)}")
        if slot_joint == 3 and set(failing) == {"Shape"} or set(failing) == {"MI"}:
            print(f"  The grille faces the SAME Sig3/Sig4 tension as the slot generator.")
            print(f"  This suggests the tension is a fundamental property of positional")
            print(f"  slot structure, not an artefact of any specific generative model.")
        else:
            print(f"  The grille fails on different signatures than the slot generator,")
            print(f"  suggesting its limitations are mechanism-specific.")
    else:
        print(f"\n  RESULT: Best grille is only {best_n}/4.  The Cardan grille model")
        print(f"  is a worse fit for the VMS joint profile than the slot generator.")


# ============================================================================
# MAIN ANALYSIS PARTS
# ============================================================================

def run_main(n_runs, base_seed, n_words, n_shuffles, english_path=None):
    # --- Pool-separated configs (G0-G5) ---
    cfgs = grille_configs(n_words)

    # --- Honest table configs (G8-G10) ---
    print(f"  Building source corpora for honest table configs (G8/G9/G10)...",
          end="", flush=True)
    corpora = build_honest_source_corpora()
    print(f"  done.")
    honest  = grille_honest_configs(n_words, corpora)

    # --- Row-sequential configs (G_seq) ---
    print(f"  Building source words for row-sequential configs...",
          end="", flush=True)
    seq_sources = build_sequential_source_words(english_path, n_words)
    print(f"  done.")
    sequential  = grille_sequential_configs(n_words, seq_sources)

    all_agg = []
    for cfg in cfgs + honest + sequential:
        table_info = (f"table={cfg.table_rows}x{cfg.table_cols}"
                      if cfg.mode != "SEQUENTIAL"
                      else f"source={len(cfg.source_words or [])} words")
        print(f"  Running: {cfg.label}  "
              f"({n_runs} runs, {cfg.n_graphemes} graphemes, {table_info})...",
              end="", flush=True)
        results = run_grille_config(cfg, n_runs, base_seed, n_shuffles)
        agg     = ev.aggregate(results)
        all_agg.append(agg)
        _, nm = ev.joint_profile_match(agg)
        print(f"  E->S={agg['es_pct_mean']:.1f}%  "
              f"MI={agg['mi_orig_mean']:.4f}  "
              f"Shape={agg['shape']}  {nm}/4")

    n_sep  = len(cfgs)
    n_hon  = len(honest)
    sep_agg   = all_agg[:n_sep]
    hon_agg   = all_agg[n_sep:n_sep + n_hon]
    seq_agg   = all_agg[n_sep + n_hon:]

    print_grille_table(sep_agg,
        "GRILLE RESULTS — POOL-SEPARATED (G0-G5, circular on Sig1)")
    print_grille_table(hon_agg,
        "GRILLE RESULTS — HONEST TABLE (G8-G10, no pre-imposed pool separation)")
    if seq_agg:
        print_grille_table(seq_agg,
            "GRILLE RESULTS — ROW-SEQUENTIAL (G_seq, honest MI test)")
        print(f"  Key: MI in G_seq_English is bounded above by English source MI.")
        print(f"  Net sequential signal = MI_orig - MI_shuf (see sensitivity sweep).")
        print(f"  G_seq_Random is the null: net signal should be ~0 regardless of p_jump.")
    print_grille_interpretation(all_agg)
    return all_agg


def run_falsification(n_runs, base_seed, n_words, n_shuffles):
    cfgs    = grille_nearmiss_configs(n_words)
    all_agg = []
    for cfg in cfgs:
        print(f"  Running: {cfg.label}  ({n_runs} runs)...",
              end="", flush=True)
        results = run_grille_config(cfg, n_runs, base_seed, n_shuffles)
        agg     = ev.aggregate(results)
        all_agg.append(agg)
        _, nm = ev.joint_profile_match(agg)
        print(f"  E->S={agg['es_pct_mean']:.1f}%  "
              f"MI={agg['mi_orig_mean']:.4f}  "
              f"Shape={agg['shape']}  {nm}/4")

    print_grille_table(all_agg, "GRILLE NEAR-MISS FALSIFICATION")
    print_grille_interpretation(all_agg)
    return all_agg


def run_sensitivity(n_runs, base_seed, n_words, n_shuffles):
    sweeps = [
        ("Blank Probability",    sens_blank_prob(n_words)),
        ("Number of Holes",      sens_n_holes(n_words)),
        ("Table Columns",        sens_table_cols(n_words)),
        ("Column Skew (alpha)",  sens_col_skew(n_words)),
        ("Table Rows",           sens_table_rows(n_words)),
    ]
    for title, cfgs in sweeps:
        print(f"\n  --- {title} ---")
        agg_list = []
        for cfg in cfgs:
            print(f"  Running: {cfg.label}  ({n_runs} runs)...",
                  end="", flush=True)
            agg = ev.aggregate(
                run_grille_config(cfg, n_runs, base_seed, n_shuffles))
            agg_list.append(agg)
            _, nm = ev.joint_profile_match(agg)
            print(f"  E->S={agg['es_pct_mean']:.1f}%  "
                  f"MI={agg['mi_orig_mean']:.4f}  {nm}/4")
        print_grille_sens_table(agg_list, title)


# ============================================================================
# MAIN
# ============================================================================

def main():
    ap = argparse.ArgumentParser(
        description="Cardan Grille — VMS Structural Signature Test")
    ap.add_argument("--runs",  type=int, default=20)
    ap.add_argument("--seed",  type=int, default=42)
    ap.add_argument("--words", type=int, default=37000)
    ap.add_argument("--part",  default="all",
                    choices=["all", "main", "sensitivity", "falsify"])
    ap.add_argument("--fast",  action="store_true",
                    help="3 MI shuffles instead of 10")
    ap.add_argument("--english-path", default=None,
                    dest="english_path",
                    help="Path to plain-text English corpus "
                         "(e.g. data/english.txt). If not set, falls back "
                         "to tiled Moby Dick snippet (~5k words).")
    args = ap.parse_args()

    n_shuffles = 3 if args.fast else 10
    mode       = "FAST" if args.fast else "FULL"

    print(f"\n{'#'*70}")
    print(f"#  CARDAN GRILLE — VMS STRUCTURAL SIGNATURE TEST")
    print(f"#  runs={args.runs}  seed={args.seed}  words={args.words}  mode={mode}")
    print(f"#  Grille types: RANDOM (Rugg), SHIFT, ROTATE, WEIGHTED, SEQUENTIAL")
    print(f"#  Specialisation: NONE/UNIFORM, SPLIT, GRADIENT, BLANK_GRADIENT")
    print(f"#  Evaluation: same 4-signature pipeline as signatures_v26.py")
    if args.english_path:
        print(f"#  English corpus: {args.english_path}")
    else:
        print(f"#  English corpus: fallback snippet (use --english-path for full)")
    print(f"{'#'*70}")

    main_agg  = []
    false_agg = []

    if args.part in ("all", "main"):
        print(f"\n{'='*70}\n  PART 1: MAIN GRILLE ABLATIONS\n{'='*70}\n")
        main_agg = run_main(args.runs, args.seed, args.words, n_shuffles,
                            english_path=args.english_path)

    if args.part in ("all", "falsify"):
        print(f"\n{'='*70}\n  PART 2: NEAR-MISS FALSIFICATION\n{'='*70}\n")
        false_agg = run_falsification(args.runs, args.seed, args.words, n_shuffles)

    if args.part in ("all", "sensitivity"):
        print(f"\n{'='*70}\n  PART 3: SENSITIVITY ANALYSIS\n{'='*70}\n")
        run_sensitivity(args.runs, args.seed, args.words, n_shuffles)

    if main_agg or false_agg:
        all_grille = main_agg + false_agg
        print_comparison_summary(all_grille)

    print(f"\n{'#'*70}\n#  COMPLETE\n{'#'*70}\n")


if __name__ == "__main__":
    main()
